# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8d0d3c4a283e205df8e5237b9450598353192faf50dbb9f994d560330cd90643a052eaae49530ffa6914ec6ec6c6fc0c7de7eeb861ca683b5463bbbf464dab

test:
  secret_key_base: ccc01f6743675aee9c8b4f2057aef7def93df95e0618af722cdaea498b0af71918910d924fd92d413d1ea8e8fcd1487b1a123983a8536310bf206e8307e60a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
